import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import StatCard from '../components/StatCard';
import InsightCard from '../components/InsightCard';
import InfoTip from '../components/InfoTip';
import { formatNumber, formatCurrency } from '../utils/format';

export default function OverviewTab({ data }) {
  const ccodeSix = data.by_ccode.slice(0, 6);

  return (
    <div className="space-y-6">
      {/* Stat cards */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard title="Total Organizations" value={formatNumber(data.overview.total_orgs)} info={`Count of all tax-exempt organizations registered in ${data.state_name} in the IRS Business Master File, including those filing Form 990, 990-EZ, 990-PF, and 990-N.`} />
        <StatCard title="Core Nonprofit Types" value={formatNumber(data.overview.priority_orgs)} subtitle="c3, c4, c6, c19" info="Organizations classified under 501(c)(3) charitable, 501(c)(4) social welfare, 501(c)(6) business leagues, or 501(c)(19) veterans' organizations — the types most relevant to nonprofit sector analysis." />
        <StatCard title="Total Revenue" value={formatCurrency(data.overview.total_revenue)} info="Sum of total revenue (Form 990 Part I, Line 12) from each organization's most recent filing. Only includes organizations with available 990/990-EZ/990-PF data." />
        <StatCard title="Total Assets" value={formatCurrency(data.overview.total_assets)} info="Sum of total assets at end of year (Form 990 Part X, Line 16) from each organization's most recent filing." />
      </div>

      {/* Insight cards */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <InsightCard
          title="National Benchmark"
          value={`~${data.overview.national_nonprofit_gdp_pct}% of GDP`}
          description="Nonprofit sector nationally (BEA)"
          color="blue"
          info="Bureau of Economic Analysis (BEA) Nonprofit Institutions Serving Households (NPISH) satellite account. Measures value added by nonprofits as a share of national GDP. State-level figures are not available from BEA."
        />
        <InsightCard
          title="Rural Presence"
          value={formatNumber(data.overview.rural_orgs)}
          description={`${Math.round(data.overview.rural_orgs / data.overview.total_orgs * 100)}% of orgs serve rural communities`}
          color="green"
          info="Organizations located in communities with population under 2,500 based on Census population estimates. Each organization's city is matched to U.S. Census Bureau population estimates for incorporated places; cities with no match count as rural."
        />
        <InsightCard
          title="Revenue Concentration"
          value={`Top 10 = ${data.overview.top10_pct}%`}
          description="High concentration in largest orgs"
          color="purple"
          info="Percentage of total sector revenue generated by the 10 largest organizations by annual revenue. Calculated from most recent Form 990 filings."
        />
      </div>

      {/* Charts */}
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        {/* Organizations by Type */}
        <div className="bg-white rounded-lg p-6 border border-slate-200">
          <h3 className="font-semibold text-slate-900 mb-4">Organizations by Type<InfoTip text="Count of organizations by IRS subsection code. Priority types (c3, c4, c6, c19) are highlighted as most relevant to sector analysis." /></h3>
          <ResponsiveContainer width="100%" height={280}>
            <BarChart data={ccodeSix} layout="vertical" margin={{ left: 0, right: 16, top: 4, bottom: 4 }}>
              <XAxis type="number" tick={{ fontSize: 11 }} tickFormatter={formatNumber} />
              <YAxis type="category" dataKey="code" width={85} tick={{ fontSize: 11 }} />
              <Tooltip formatter={(value) => formatNumber(value)} />
              <Bar dataKey="count">
                {ccodeSix.map((entry, index) => (
                  <Cell
                    key={`cell-${index}`}
                    fill={entry.priority ? '#1b4965' : '#94a3b8'}
                  />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
          <p className="text-xs text-slate-400 italic mt-3">Source: IRS Form 990, 990-EZ and 990-PF filings (SOI annual extracts)</p>
          {/* Legend */}
          <div className="flex gap-4 mt-3 text-sm text-slate-600">
            <div className="flex items-center gap-1.5">
              <div className="w-3 h-3 rounded-sm bg-[#1b4965]"></div>
              <span>Core Type</span>
            </div>
            <div className="flex items-center gap-1.5">
              <div className="w-3 h-3 rounded-sm bg-slate-400"></div>
              <span>Other</span>
            </div>
          </div>
        </div>

        {/* Data Freshness */}
        <div className="bg-white rounded-lg p-6 border border-slate-200">
          <h3 className="font-semibold text-slate-900 mb-4">Data Freshness<InfoTip text="Distribution of organizations by the tax year of their most recent available filing. 'No Filing Data' includes 990-N filers (under $50K revenue) whose returns lack financial detail." /></h3>
          <ResponsiveContainer width="100%" height={280}>
            <PieChart>
              <Pie
                data={data.by_freshness}
                dataKey="count"
                nameKey="status"
                innerRadius={60}
                outerRadius={100}
              >
                {data.by_freshness.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.color} />
                ))}
              </Pie>
              <Tooltip formatter={(value) => formatNumber(value)} />
            </PieChart>
          </ResponsiveContainer>
          <p className="text-xs text-slate-400 italic mt-3">Source: IRS Form 990, 990-EZ and 990-PF filings (SOI annual extracts)</p>
          {/* Legend */}
          <div className="grid grid-cols-2 gap-1.5 mt-2 text-sm text-slate-600">
            {data.by_freshness.map((entry, index) => (
              <div key={index} className="flex items-center gap-1.5">
                <div className="w-3 h-3 rounded-sm flex-shrink-0" style={{ backgroundColor: entry.color }}></div>
                <span>{entry.status}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Data quality note */}
      <div className="bg-white border border-slate-200 border-l-4 border-l-[#c17817] rounded-lg p-4 text-sm text-slate-700">
        <strong>Data Quality Note:</strong> {formatNumber(data.overview.no_financials)} organizations ({Math.round(data.overview.no_financials / data.overview.total_orgs * 100)}%) have no
        detailed financial data because they file Form 990-N (e-Postcard).
      </div>
    </div>
  );
}
